### PR TITLE
fix cmd line support for opt args and add support for multiple args

### PR DESCRIPTION
**Pull request by backpropper**

### CODE REVIEW

**Comment by backpropper** [comment]
I think type should be a required argument whether to use int or float.
I think block at the end does not do anything? its only used when you reserve the threads

**Comment by williamFalcon** [comment]
there’s also a string type, bool, and i assume other types supported

**Comment by backpropper** [comment]
what do they do in opt_range?

**Comment by williamFalcon** [comment]
but it’s optional in argparse, I’m not sure it should be mandatory. Perhaps have good error checking to let people know that something won’t work with a type?

**Comment by williamFalcon** [comment]
yeah in opt range nothing. I didn’t read this carefully haha. i guess in opt-range it shoild be required

**Pull request merged**
