### PR TITLE
Clean up API and enable random search

### PR DESCRIPTION
**Pull request by Alok**
A bunch of changes, but mostly striving for a cleaner API naming scheme
and proper random search.

This isn't backwards compatible at all, but this library is newish, and
I figured it was best to bite the bullet and change it before it hits
v1.0.

### CODE REVIEW

**Comment by Alok** [comment]
I may have butchered the doc generation by editing some stuff by hand.

**Comment by williamFalcon** [comment]
Looks like you made a lot of changes, thanks for your addition! I will read through these changes over the next few days.

Wondering if you can summarize big changes in the comments. Also, what did you mean by better random search? It was already working fine

**Comment by Alok** [comment]
Oh, I just mean that this random search is a bit simpler in that it just picks N points in the range `low,high` rather than creating a grid and picking from that. I don't know if it's conclusively better, I'd have to do a proof or at least a few tests of that. I think it is more in line with what people say when they mean random search.

**Comment by Alok** [comment]
Main changes:

- Most of the api functions are renamed. Search for `->` in the commit messages to see which.
- Random search is changed. Log scale searching is added.
- Markdown is formatted with Pandoc
- Python is formatted with YAPF (config used added to the `setup.cfg` file)

**Comment by williamFalcon** [comment]
Initial thoughts on some of the renames. The renames look good, but what do you think about keeping the add_ before the calls? The add_ removes the ambiguity of what the API is, and allows for intuitive thinking about what it can do. It also allows for autocomplete to be super helpful instead of having to load the docs to figure out what that thing was called. Instead, you can just remember one thing "add_" and use that as a way to "searh" the docs on the fly. It's more about usability for the user than anything else.

So, changing **add_metric_row** to **add_log** makes more sense to me than **log**.

**Comment by Alok** [comment]
I thought about that, actually. The thing is that the API is really small, and if someone wants to search it, it's easy to do on the doc site. Since it's small, it's pretty easy to remember the 5 or so commands you need.

I made them short to encourage using them as often as possible, since they shine when everything ends up in a log.

Commands like `tag` and `log` are verbs by themselves (you tag things and you log them) and seem unambiguous after a brief read of the docs.

Any user will have to at least skim the README, which clears up what these do anyway.

**Comment by williamFalcon** [comment]
Ok. Good points. Let me review the code over the next day or so. Good additions!

**Comment by Alok** [comment]
Let me know if you want an explanation of anything else, I'd be more than happy to walk through it.

**Comment by williamFalcon** [comment]
sure!. Just a bit busy with work right now. Would simplify things to separate all the documentation changes into one PR and all the code changes into another

**Comment by williamFalcon** [comment]
@Alok great job! These changes are great. Would love add a few more features before we cut the next breaking version. What do you think?

Sorry for the delay! Been 3x busier than normal haha these weeks

**Comment by williamFalcon** [comment]
@Alok these changes are great. Let's talk offline about new things on the roadmap? Would be curious to hear your ideas as well.   
email me  [waf2107] at columbia  dott    edu

**Pull request merged**
